In [1]:
# File for classification

In [2]:
from os.path import join
from google.colab import drive

# path to your project on Google Drive
MY_GOOGLE_DRIVE_PATH = 'My Drive/Capstone Project'
ROOT = '/content/gdrive/'
drive.mount(ROOT)

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).


In [3]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from collections import Counter
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.compose import make_column_transformer

In [4]:
#Setting Random Seed
np.random.seed(0)
torch.manual_seed(0)

In [5]:
#Setting Device
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


In [6]:
# import churn and telescope datasets
data_dir = ROOT + MY_GOOGLE_DRIVE_PATH + '/Edge/data/'

churn = pd.read_csv(data_dir + 'churn.csv')
churn.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

telescope = pd.read_table(data_dir + 'telescope.dat', header=None, delimiter=',')
telescope.columns = ['FLength', 'FWidth', 'FSize', 'FConc', 'FConc1', 'FAsym', 
                     'FM3Long', 'FM3Trans', 'FAlpha', 'FDist', 'Class']

print('Shape - Churn: {} & Telescope: {}'.format(churn.shape, telescope.shape))

Shape - Churn: (10000, 11) & Telescope: (19020, 11)


In [7]:
churn.head()

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [8]:
churn["Exited"].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [9]:
churn["Geography"].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [10]:
churn["Gender"].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [11]:
# preprocess churn & telescope data, convert numpy to tensor
preprocess = make_column_transformer(
    (OneHotEncoder(), ['Geography', 'Gender']), remainder = StandardScaler())

In [12]:
data = preprocess.fit_transform(churn.iloc[:, :-1])
target = np.array(churn.iloc[:, -1])
print('\nClass Distribution - Churn:', Counter(target))
data = data.astype(np.float32)
target = target.astype(np.long)

churn = {'data': torch.from_numpy(data), 'target': torch.from_numpy(target)}


Class Distribution - Churn: Counter({0: 7963, 1: 2037})


In [13]:
churn_dataset = torch.utils.data.TensorDataset(churn["data"],churn["target"])

In [14]:
telescope.head()

FLength    FWidth   FSize   FConc  ...  FM3Trans   FAlpha     FDist  Class
0   28.7967   16.0021  2.6449  0.3918  ...   -8.2027  40.0920   81.8828      g
1   31.6036   11.7235  2.5185  0.5303  ...   -9.9574   6.3609  205.2610      g
2  162.0520  136.0310  4.0612  0.0374  ...  -45.2160  76.9600  256.7880      g
3   23.8172    9.5728  2.3385  0.6147  ...   -7.1513  10.4490  116.7370      g
4   75.1362   30.9205  3.1611  0.3168  ...   21.8393   4.6480  356.4620      g

[5 rows x 11 columns]

In [15]:
telescope["Class"].value_counts()

g    12332
h     6688
Name: Class, dtype: int64

In [16]:
telescope.describe()

FLength        FWidth  ...        FAlpha         FDist
count  19020.000000  19020.000000  ...  19020.000000  19020.000000
mean      53.250154     22.180966  ...     27.645707    193.818026
std       42.364855     18.346056  ...     26.103621     74.731787
min        4.283500      0.000000  ...      0.000000      1.282600
25%       24.336000     11.863800  ...      5.547925    142.492250
50%       37.147700     17.139900  ...     17.679500    191.851450
75%       70.122175     24.739475  ...     45.883550    240.563825
max      334.177000    256.382000  ...     90.000000    495.561000

[8 rows x 10 columns]

In [17]:
scaler = StandardScaler()

In [18]:
data = scaler.fit_transform(telescope.iloc[:, :-1])
target = LabelEncoder().fit_transform(telescope.Class)
print('\nClass Distribution - Telescope:', Counter(target))

data = data.astype(np.float32)
target = target.astype(np.long)

telescope = {'data': torch.from_numpy(data), 'target': torch.from_numpy(target)}


Class Distribution - Telescope: Counter({0: 12332, 1: 6688})


In [19]:
telescope_dataset = torch.utils.data.TensorDataset(telescope["data"],telescope["target"])

In [20]:
#hyperparameters

hidden_size = 5
num_classes = 2
num_epochs = 5
batch_size = 100
learning_rate = 0.001

In [21]:
#Model Architecture
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size) 
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)  
    
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

In [22]:
train_loader = torch.utils.data.DataLoader(dataset=churn_dataset, 
                                           batch_size=batch_size, 
                                           shuffle=True)

In [23]:
input_size = churn["data"].shape[1]
model_churn = NeuralNet(input_size, hidden_size, num_classes).to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_churn.parameters(), lr=learning_rate)  

In [24]:
print(model_churn)

NeuralNet(
  (fc1): Linear(in_features=13, out_features=5, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=5, out_features=2, bias=True)
)


In [25]:
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (features, labels) in enumerate(train_loader):  
        # Move tensors to the configured device
        features = features.to(device)
        labels = labels.to(device)
        
        # Forward pass
        outputs = model_churn(features)
        loss = criterion(outputs, labels)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))


Epoch [1/5], Step [100/100], Loss: 0.5410
Epoch [2/5], Step [100/100], Loss: 0.4922
Epoch [3/5], Step [100/100], Loss: 0.4504
Epoch [4/5], Step [100/100], Loss: 0.3604
Epoch [5/5], Step [100/100], Loss: 0.4993


In [26]:
l = [module for module in model_churn.children() if type(module) != nn.Sequential]
print(l)
for i in l:
  try:
    print('Layer: {} weight:{}'.format(i,i.weight))
  except:
    continue

[Linear(in_features=13, out_features=5, bias=True), ReLU(), Linear(in_features=5, out_features=2, bias=True)]
Layer: Linear(in_features=13, out_features=5, bias=True) weight:Parameter containing:
tensor([[-0.0864,  0.0676, -0.2783, -0.2585, -0.2018,  0.0066,  0.0375,  0.1235,
          0.0326,  0.0747, -0.0436, -0.0262, -0.1691],
        [-0.2319, -0.1648, -0.0956,  0.0858,  0.0710, -0.1671,  0.0069,  0.0429,
          0.1638,  0.1675,  0.1183, -0.0709,  0.0955],
        [ 0.4540, -0.1149,  0.1110,  0.0815,  0.1665,  0.3673, -0.2699, -0.1216,
         -0.3564, -0.0590, -0.0800,  0.3081, -0.0461],
        [ 0.3311,  0.0950,  0.1657,  0.1592,  0.0199, -0.1524, -0.3282,  0.3414,
          0.2048, -0.1104,  0.1747,  0.2841,  0.1523],
        [ 0.2829,  0.1286,  0.4235, -0.0565,  0.2739, -0.0910, -0.4560, -0.0566,
         -0.0262,  0.1511, -0.0297,  0.0409, -0.0612]], device='cuda:0',
       requires_grad=True)
Layer: Linear(in_features=5, out_features=2, bias=True) weight:Parameter contai

In [27]:
train_loader = torch.utils.data.DataLoader(dataset=telescope_dataset, 
                                           batch_size=batch_size, 
                                           shuffle=True)

In [28]:
input_size = telescope["data"].shape[1]
model_telescope = NeuralNet(input_size, hidden_size, num_classes).to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_telescope.parameters(), lr=learning_rate)  

In [29]:
print(model_telescope)

NeuralNet(
  (fc1): Linear(in_features=10, out_features=5, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=5, out_features=2, bias=True)
)


In [30]:
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (features, labels) in enumerate(train_loader):  
        # Move tensors to the configured device
        features = features.to(device)
        labels = labels.to(device)
        
        # Forward pass
        outputs = model_telescope(features)
        loss = criterion(outputs, labels)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))


Epoch [1/5], Step [100/191], Loss: 0.6065
Epoch [2/5], Step [100/191], Loss: 0.4885
Epoch [3/5], Step [100/191], Loss: 0.3402
Epoch [4/5], Step [100/191], Loss: 0.4141
Epoch [5/5], Step [100/191], Loss: 0.4768


In [31]:
l = [module for module in model_telescope.children() if type(module) != nn.Sequential]
print(l)
for i in l:
  try:
    print('Layer: {} weight:{}'.format(i,i.weight))
  except:
    continue

[Linear(in_features=10, out_features=5, bias=True), ReLU(), Linear(in_features=5, out_features=2, bias=True)]
Layer: Linear(in_features=10, out_features=5, bias=True) weight:Parameter containing:
tensor([[-0.5308, -0.0077,  0.4260, -0.5823, -0.4349, -0.0803,  0.2500, -0.0241,
         -0.5900,  0.0134],
        [-0.1393, -0.2644, -0.1518,  0.0024, -0.4289,  0.0300,  0.1299,  0.0241,
         -0.9110,  0.2471],
        [ 0.7236,  0.1661, -0.0161, -0.3977, -0.0416, -0.0188, -0.1537,  0.0290,
          0.5282, -0.0181],
        [-0.1120, -0.4191,  0.3245,  0.1274,  0.1254,  0.4344,  0.5038,  0.0107,
          0.0055,  0.0985],
        [ 0.1704, -0.0345,  0.3293,  0.0144, -0.0237, -0.2759, -0.0182, -0.0754,
          0.4712,  0.4365]], device='cuda:0', requires_grad=True)
Layer: Linear(in_features=5, out_features=2, bias=True) weight:Parameter containing:
tensor([[ 0.1503,  0.5413, -0.6207, -0.2329, -0.2639],
        [-0.7058, -0.4487,  0.3611,  0.6021,  0.6992]], device='cuda:0',
       r